/* BW050-A, Config based on ASUS RT-AC51U */

#define BOARD_PID		"BW050-A"
#define BOARD_NAME		"BW050-A"
#define BOARD_DESC		"UNKNOWN BW050-A Wireless Router"
#define BOARD_VENDOR_NAME	"UNKNOWN"
#define BOARD_VENDOR_URL	"https://www.baidu.com/"
#define BOARD_MODEL_URL		"https://www.baidu.com/s?wd=BW050-A"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	1
#define BOARD_GPIO_BTN_WPS	2
#define BOARD_GPIO_LED_ALL	10
#undef  BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_POWER	9
#undef  BOARD_GPIO_LED_LAN
#undef  BOARD_GPIO_LED_WAN
#define BOARD_GPIO_LED_USB	14
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	1
#define BOARD_NUM_ANT_5G_RX	1
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
